//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrpSkuRepository.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkuInventoryDb
    {
        public int ID { get; set; }
        public string Item_Description { get; set; }
        public string Comment { get; set; }
        public string Source { get; set; }
        public string Item_Number { get; set; }
        public string Product { get; set; }
        public Nullable<int> Term { get; set; }
        public string InUse { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> MfnFloorPrice { get; set; }
        public Nullable<int> LicenseTypeId { get; set; }
        public Nullable<int> SkuTypeId { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
        public string BaseSku { get; set; }
        public Nullable<int> SkuCategoryId { get; set; }
        public Nullable<decimal> SkuPrice { get; set; }
        public Nullable<decimal> MsrpPrice { get; set; }
        public string SkuCurrency { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedUTC { get; set; }
        public System.DateTime ChangedUTC { get; set; }
        public Nullable<int> OrpProductId { get; set; }
    }
}
